name: cdk synth ( dev )

on:
  push:
    branches:
      - '*'

jobs:
  cdk_synth:
    name: cdk synth
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.41.0'
          working_dir: 'cdk'
          cdk_args: '--context stage=dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'
